Pixi for installation and execution
MaMMoS-project/MagneticMaterialsOntology pull request #2
Opened 2024-12-10 15:13 UTC by fangohr

2024-12-16 19:38 UTC, samjrholt requested changes
Looks good. I've successfully installed and run the first two tasks but get an error running the `docs` task

2024-12-16 19:38 UTC, samjrholt commented on pixi.toml
> +docs = "ontodoc --format simple-html magnetic_material_mammos.ttl doc/magnetic_material_mammos.html"
Running `pixi run docs` gives an error 

```
pixi run docs
✨ Pixi task (docs): ontodoc --format simple-html magnetic_material_mammos.ttl doc/magnetic_material_mammos.html
Traceback (most recent call last):
  File "/home/sam/repos/MagneticMaterialsOntology/.pixi/envs/default/bin/ontodoc", line 293, in <module>
    main()
    ~~~~^^
  File "/home/sam/repos/MagneticMaterialsOntology/.pixi/envs/default/bin/ontodoc", line 278, in main
    docpp.process()
    ~~~~~~~~~~~~~^^
  File "/home/sam/repos/MagneticMaterialsOntology/.pixi/envs/default/lib/python3.13/site-packages/ontopy/ontodoc.py", line 1138, in process
    self.process_alls()
    ~~~~~~~~~~~~~~~~~^^
  File "/home/sam/repos/MagneticMaterialsOntology/.pixi/envs/default/lib/python3.13/site-packages/ontopy/ontodoc.py", line 1017, in process_alls
    self.lines[i:i] = self.ontodoc.itemsdoc(
                      ~~~~~~~~~~~~~~~~~~~~~^
        items, int(opts.header_level)  # pylint: disable=no-member
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ).split("\n")
    ^
  File "/home/sam/repos/MagneticMaterialsOntology/.pixi/envs/default/lib/python3.13/site-packages/ontopy/ontodoc.py", line 451, in itemsdoc
    doc.append(self.itemdoc(item, header_level))
               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/repos/MagneticMaterialsOntology/.pixi/envs/default/lib/python3.13/site-packages/ontopy/ontodoc.py", line 340, in itemdoc
    point=asstring(prop, link_style, ontology=onto),
          ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/repos/MagneticMaterialsOntology/.pixi/envs/default/lib/python3.13/site-packages/ontopy/utils.py", line 262, in asstring
    string = asstring(
        expr.value, link, recursion_depth + 1, ontology=ontology
    )
  File "/home/sam/repos/MagneticMaterialsOntology/.pixi/envs/default/lib/python3.13/site-packages/ontopy/utils.py", line 314, in asstring
    raise RuntimeError(f"Unknown expression: {expr!r} (type: {type(expr)!r})")
RuntimeError: Unknown expression: None (type: <class 'NoneType'>)
```

2024-12-16 19:38 UTC, samjrholt commented on src/README.md
> +   git clone https://github.com/MaMMoS-project/MagneticMaterialsOntology.git
```suggestion
   `git clone https://github.com/MaMMoS-project/MagneticMaterialsOntology.git`
```

2024-12-16 19:54 UTC, thomasschrefl commented
> Looks good. I've successfully installed and run the first two tasks but get an error running the `docs` task

I do not where this error comes from. By the way in the meantime, I changed doc section of the create.sh script.
We should also update the pixi task accordlingy.

2024-12-17 13:07 UTC, fangohr commented
I fixed the error that Tom saw by merging the changes on the `main` branch into this PR.

2024-12-18 09:01 UTC, fangohr commented
This is ready to be merged, I think.

2024-12-18 12:08 UTC, fangohr commented
We still have an error that occurs, but that has nothing todo with the addition of the pixi-based software installation or task execution: it also occurs on main when running the `create.sh` script.

With this merge request , we can and will do the build  (equivalent to running `create.sh`) for every change to the repository, and that will tell us early if something is broken. 

I have added a "badge" like this 

[![build](https://github.com/MaMMoS-project/MagneticMaterialsOntology/actions/workflows/build.yaml/badge.svg)](https://github.com/MaMMoS-project/MagneticMaterialsOntology/actions/workflows/build.yaml)

to the README (at the very bottom for now) to quickly see the status.

@samjrholt are you happy for this to be merged?

2024-12-18 12:45 UTC, samjrholt approved these changes

2024-12-18 14:06 UTC, merged